import courses from '../../../../courses';

const EnergyEngineering_Minor_Courses = [
    {
      "Division": "Lower Division",
      "Requirement": "Calculus I",
      "Category": "",
      "Course": courses["MATH 1A"],
    },
    {
      "Division": "Lower Division",
      "Requirement": "Calculus II",
      "Category": "",
      "Course": courses["MATH 1B"],
    },
    {
      "Division": "Lower Division",
      "Requirement": "Multivariable Calculus",
      "Category": "",
      "Course": courses["MATH 53"],
    },
    {
      "Division": "Lower Division",
      "Requirement": "Linear Algebra",
      "Category": "",
      "Course": courses["MATH 54"],
    },
    {
      "Division": "Lower Division",
      "Requirement": "Chemistry",
      "Category": "",
      "Course": courses["CHEM 1A"],
    },
    {
      "Division": "Lower Division",
      "Requirement": "Chemistry",
      "Category": "",
      "Course": courses["CHEM 3A"],
    },
    {
      "Division": "Lower Division",
      "Requirement": "Physics I",
      "Category": "",
      "Course": courses["PHYSICS 7A"],
    },
    {
      "Division": "Lower Division",
      "Requirement": "Physics II",
      "Category": "",
      "Course": courses["PHYSICS 7B"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement I",
      "Category": "",
      "Course": courses["ME 40"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement I",
      "Category": "",
      "Course": courses["ENGIN 115"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement II",
      "Category": "",
      "Course": courses["EE 137A"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement III",
      "Category": "",
      "Course": courses["ER C100"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement III",
      "Category": "",
      "Course": courses["CIV ENG C106"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement III",
      "Category": "",
      "Course": courses["CIV ENG 107"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement III",
      "Category": "",
      "Course": courses["CIV ENG 111"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["ARCH 140"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["CY PLAN 119"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["CIV ENG C106"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["CIV ENG 107"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["CIV ENG 111"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["CIV ENG 115"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["CIV ENG 156"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["EL ENG 134"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["EL ENG 137B"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["ER C100"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["ER 101"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["ER C180"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["ENGIN 120"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["ENGIN 194"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["ENVECON 147"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["ENVECON C151"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["ENVECON 153"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["ENVECON 154"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["ESPM 102D"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["GEOG 142"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["IEOR 172"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["STAT 134"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["MAT SCI 136"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["MEC ENG 106"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["MEC ENG 109"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["NUC ENG 161"],
    },
    {
      "Division": "Upper Division",
      "Requirement": "Requirement IV",
      "Category": "",
      "Course": courses["POLECON 101"],
    }
  ]

  export default EnergyEngineering_Minor_Courses;